# SwiftLint Configuration for EnvantoBarkod

# Dahil edilecek dosyalar
included:
  - .
  
# Hariç tutulacak dosyalar ve klasörler
excluded:
  - .build
  - .git
  - .github
  - build
  - DerivedData
  - EnvantoBarkod.xcodeproj
  - Assets.xcassets

# Devre dışı bırakılacak kurallar
disabled_rules:
  - trailing_whitespace # Satır sonu boşlukları
  - todo # TODO yorumları
  - line_length # Satır uzunluğu (özel ayar yapacağız)

# Sadece uyarı verecek kurallar
opt_in_rules:
  - empty_count
  - empty_string
  - force_unwrapping
  - implicitly_unwrapped_optional
  - overridden_super_call
  - redundant_nil_coalescing
  - unused_optional_binding
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces

# Kural ayarları
line_length:
  warning: 120
  error: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 5
  error: 8

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level:
    warning: 2
    error: 3
  statement_level:
    warning: 5
    error: 10

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - url
    - api
    - db

# Özel kurallar
custom_rules:
  # Print statement kontrolü
  no_print:
    name: "No Print Statements"
    regex: 'print\('
    message: "Print statements should not be used in production code"
    severity: warning
    
  # Force unwrapping kontrolü
  force_unwrap_warning:
    name: "Force Unwrap Warning"
    regex: '\!\s*$'
    message: "Avoid force unwrapping, use safe unwrapping instead"
    severity: warning
    
  # TODO/FIXME kontrolü
  todo_fixme:
    name: "TODO and FIXME"
    regex: '(TODO|FIXME):'
    message: "TODO and FIXME should be resolved before release"
    severity: warning

# Dosya başlığı kontrolü
file_header:
  required_pattern: |
                    \/\/
                    \/\/.*\.swift
                    \/\/  EnvantoBarkod
                    \/\/
                    \/\/  Created by .* on .*\.
                    \/\/

# Reporter türü
reporter: "xcode"