version: 1

workflows:
  main-workflow:
    name: Envanto Barkod Production Build
    description: Main workflow for building and distributing to TestFlight
    
    # Ne zaman çalışacak
    trigger:
      branch: main
      
    # Build ayarları
    build:
      xcode_version: latest
      scheme: EnvantoBarkod
      configuration: Release
      
    # Build sonrası işlemler
    post_build:
      # TestFlight'a otomatik upload
      - action: testflight
        distribute: true
        groups: 
          - "App Store Connect Users"
        notify_external_testers: false
        changelog: "Otomatik build - GitHub commit: $CI_COMMIT_SHA"
        
  develop-workflow:
    name: Envanto Barkod Development Build
    description: Development workflow for testing
    
    # Ne zaman çalışacak
    trigger:
      branch: develop
      
    # Build ayarları
    build:
      xcode_version: latest
      scheme: EnvantoBarkod
      configuration: Debug
      
    # Build sonrası işlemler
    post_build:
      # Sadece build, TestFlight'a upload yok
      - action: archive