workflows:
  ios-testflight-auto:
    name: Envanto Barkod iOS → TestFlight
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.envanto.barcode.ios
      vars:
        XCODE_WORKSPACE: "EnvantoBarkod.xcodeproj"
        XCODE_SCHEME: "EnvantoBarkod"
        BUNDLE_ID: "com.envanto.barcode.ios"
        APP_STORE_APPLE_ID: 6749488468
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get CocoaPods dependencies
        script: |
          if [ -f "Podfile" ]; then
            pod install
          else
            echo "Podfile bulunamadı, CocoaPods adımı atlanıyor"
          fi
      - name: Set up code signing
        script: |
          echo "🔐 Setting up App Store code signing..."
          xcode-project use-profiles
      - name: Increment build number
        script: |
          # Build number'ı otomatik artır (timestamp)
          BUILD_NUMBER=$(date +%Y%m%d%H%M)
          echo "🔢 Setting build number to: $BUILD_NUMBER"
          
          # Info.plist'te build number güncelle
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUMBER" Info.plist || true
          
          echo "✅ Build number updated: $BUILD_NUMBER"
      - name: Build for App Store
        script: |
          echo "🏗️ Building for App Store distribution..."
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --config "Release"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - samet.bicen@icloud.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - App Store Connect Users
        submit_to_app_store: false

  ios-testflight-debug:
    name: Envanto Barkod iOS → TestFlight (Debug)
    max_build_duration: 90
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.envanto.barcode.ios
      vars:
        XCODE_WORKSPACE: "EnvantoBarkod.xcodeproj"
        XCODE_SCHEME: "EnvantoBarkod"
        BUNDLE_ID: "com.envanto.barcode.ios"
        APP_STORE_APPLE_ID: 6749488468
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get CocoaPods dependencies
        script: |
          if [ -f "Podfile" ]; then
            pod install
          else
            echo "Podfile bulunamadı, CocoaPods adımı atlanıyor"
          fi
      - name: Set up code signing
        script: |
          echo "🔐 Setting up App Store code signing..."
          xcode-project use-profiles
      - name: Increment build number
        script: |
          # Debug için farklı build number pattern
          BUILD_NUMBER="$(date +%Y%m%d%H%M)d"
          echo "🔢 Setting debug build number to: $BUILD_NUMBER"
          
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUMBER" Info.plist || true
          
          echo "✅ Debug build number updated: $BUILD_NUMBER"
      - name: Build for TestFlight (Debug Config)
        script: |
          echo "🏗️ Building debug version for TestFlight..."
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --config "Debug"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - samet.bicen@icloud.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - App Store Connect Users
        submit_to_app_store: false

  ios-development-build:
    name: Envanto Barkod iOS Development Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      ios_signing:
        distribution_type: development
        bundle_identifier: com.envanto.barcode.ios
      vars:
        XCODE_WORKSPACE: "EnvantoBarkod.xcodeproj"
        XCODE_SCHEME: "EnvantoBarkod"
        BUNDLE_ID: "com.envanto.barcode.ios"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get CocoaPods dependencies
        script: |
          if [ -f "Podfile" ]; then
            pod install
          else
            echo "Podfile bulunamadı, CocoaPods adımı atlanıyor"
          fi
      - name: Set up development code signing
        script: |
          echo "🔐 Setting up development code signing..."
          xcode-project use-profiles
      - name: Build for development
        script: |
          echo "🏗️ Building for development..."
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --config "Debug"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - samet.bicen@icloud.com
        notify:
          success: true
          failure: true

  ios-simulator-workflow:
    name: Envanto Barkod iOS Simulator Test
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_WORKSPACE: "EnvantoBarkod.xcodeproj"
        XCODE_SCHEME: "EnvantoBarkod"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get CocoaPods dependencies
        script: |
          if [ -f "Podfile" ]; then
            pod install
          else
            echo "Podfile bulunamadı, CocoaPods adımı atlanıyor"
          fi
      - name: Build for simulator
        script: |
          xcodebuild \
            -project "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
            build
    artifacts:
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - samet.bicen@icloud.com
        notify:
          success: true
          failure: true