workflows:
  ios-testflight-auto:
    name: Envanto Barkod iOS → TestFlight
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: Codemagic developer
    environment:
      groups:
        - app_store_credentials
      vars:
        XCODE_WORKSPACE: "EnvantoBarkod.xcodeproj"
        XCODE_SCHEME: "EnvantoBarkod"
        BUNDLE_ID: "com.envanto.barcode.ios"
        APP_STORE_APPLE_ID: 6749488468
        APPLE_ID: "samet.bicen@icloud.com"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get CocoaPods dependencies
        script: |
          if [ -f "Podfile" ]; then
            pod install
          else
            echo "Podfile bulunamadı, CocoaPods adımı atlanıyor"
          fi
      - name: Set up code signing
        script: |
          echo "🔐 Setting up code signing..."
          keychain initialize
          xcode-project use-profiles
      - name: Increment build number
        script: |
          BUILD_NUMBER=$(date +%Y%m%d%H%M)
          echo "🔢 Setting build number to: $BUILD_NUMBER"
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUMBER" Info.plist || true
      - name: Create export options
        script: |
          cat > export_options.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>uploadBitcode</key>
              <false/>
              <key>compileBitcode</key>
              <false/>
              <key>teamID</key>
              <string>6F974S63AX</string>
          </dict>
          </plist>
          EOF
      - name: Build and archive
        script: |
          echo "🏗️ Building and archiving..."
          xcodebuild \
            -project "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            -archivePath build/app.xcarchive \
            archive
      - name: Export for App Store
        script: |
          echo "📦 Exporting for App Store..."
          xcodebuild \
            -exportArchive \
            -archivePath build/app.xcarchive \
            -exportPath build \
            -exportOptionsPlist export_options.plist
    artifacts:
      - build/*.ipa
      - build/app.xcarchive
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - samet.bicen@icloud.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - App Store Connect Users
        submit_to_app_store: false