workflows:
  ios-development-workflow:
    name: Envanto Barkod iOS Development Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_WORKSPACE: "EnvantoBarkod.xcodeproj"
        XCODE_SCHEME: "EnvantoBarkod"
        BUNDLE_ID: "com.envanto.barcode.ios"
        DEVELOPMENT_TEAM: "6F974S63AX"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get CocoaPods dependencies
        script: |
          if [ -f "Podfile" ]; then
            pod install
          else
            echo "Podfile bulunamadı, CocoaPods adımı atlanıyor"
          fi
      - name: Set up project for development build
        script: |
          # Xcode projesinde automatic signing ayarla
          /usr/libexec/PlistBuddy -c "Set :objects:AB1234567890123400000033:buildSettings:CODE_SIGN_STYLE Automatic" EnvantoBarkod.xcodeproj/project.pbxproj || true
          /usr/libexec/PlistBuddy -c "Set :objects:AB1234567890123400000034:buildSettings:CODE_SIGN_STYLE Automatic" EnvantoBarkod.xcodeproj/project.pbxproj || true
          /usr/libexec/PlistBuddy -c "Set :objects:AB1234567890123400000033:buildSettings:DEVELOPMENT_TEAM 6F974S63AX" EnvantoBarkod.xcodeproj/project.pbxproj || true
          /usr/libexec/PlistBuddy -c "Set :objects:AB1234567890123400000034:buildSettings:DEVELOPMENT_TEAM 6F974S63AX" EnvantoBarkod.xcodeproj/project.pbxproj || true
      - name: Build for development
        script: |
          xcodebuild \
            -project "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Debug \
            -destination 'generic/platform=iOS' \
            -allowProvisioningUpdates \
            -authenticationKeyPath ~/private_keys/AuthKey_*.p8 \
            -authenticationKeyID $APP_STORE_CONNECT_KEY_IDENTIFIER \
            -authenticationKeyIssuerID $APP_STORE_CONNECT_ISSUER_ID \
            archive \
            -archivePath build/EnvantoBarkod.xcarchive
      - name: Export IPA
        script: |
          xcodebuild \
            -exportArchive \
            -archivePath build/EnvantoBarkod.xcarchive \
            -exportPath build \
            -exportOptionsPlist export_options.plist
    artifacts:
      - build/*.ipa
      - build/EnvantoBarkod.xcarchive
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - samet.bicen@icloud.com
        notify:
          success: true
          failure: true

  ios-simulator-workflow:
    name: Envanto Barkod iOS Simulator Test
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_WORKSPACE: "EnvantoBarkod.xcodeproj"
        XCODE_SCHEME: "EnvantoBarkod"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get CocoaPods dependencies
        script: |
          if [ -f "Podfile" ]; then
            pod install
          else
            echo "Podfile bulunamadı, CocoaPods adımı atlanıyor"
          fi
      - name: Build for simulator
        script: |
          xcodebuild \
            -project "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
            build
    artifacts:
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - samet.bicen@icloud.com
        notify:
          success: true
          failure: true

  ios-simple-build:
    name: Envanto Barkod iOS Simple Build
    max_build_duration: 45
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_WORKSPACE: "EnvantoBarkod.xcodeproj"
        XCODE_SCHEME: "EnvantoBarkod"
      xcode: latest
    scripts:
      - name: Simple build test
        script: |
          # En basit build - sadece compile kontrolü
          xcodebuild \
            -project "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Debug \
            build \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
    artifacts:
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - samet.bicen@icloud.com
        notify:
          success: true
          failure: true