workflows:
  ios-testflight-workflow:
    name: Envanto Barkod iOS TestFlight Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.envanto.barcode.ios
      vars:
        XCODE_WORKSPACE: "EnvantoBarkod.xcodeproj"
        XCODE_SCHEME: "EnvantoBarkod"
        BUNDLE_ID: "com.envanto.barcode.ios"
        APP_STORE_APPLE_ID: 6749488468
        # TestFlight için gerekli bilgiler
        APP_STORE_CONNECT_ISSUER_ID: $APP_STORE_CONNECT_ISSUER_ID
        APP_STORE_CONNECT_KEY_IDENTIFIER: $APP_STORE_CONNECT_KEY_IDENTIFIER
        APP_STORE_CONNECT_PRIVATE_KEY: $APP_STORE_CONNECT_PRIVATE_KEY
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get CocoaPods dependencies
        script: |
          if [ -f "Podfile" ]; then
            pod install
          else
            echo "Podfile bulunamadı, CocoaPods adımı atlanıyor"
          fi
      - name: Increment build number
        script: |
          # Build number'ı otomatik artır
          BUILD_NUMBER=$(date +%Y%m%d%H%M)
          echo "🔢 Setting build number to: $BUILD_NUMBER"
          
          # Info.plist'te build number güncelle
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUMBER" Info.plist
          
          # Xcode project'te de güncelle
          xcrun agvtool new-version -all $BUILD_NUMBER
      - name: Build for App Store
        script: |
          echo "🏗️ Building for App Store distribution..."
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --archive-flags="-destination 'generic/platform=iOS'"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - samet.bicen@icloud.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - App Store Connect Users
        submit_to_app_store: false

  ios-testflight-debug:
    name: Envanto Barkod iOS TestFlight Debug
    max_build_duration: 90
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.envanto.barcode.ios
      vars:
        XCODE_WORKSPACE: "EnvantoBarkod.xcodeproj"
        XCODE_SCHEME: "EnvantoBarkod"
        BUNDLE_ID: "com.envanto.barcode.ios"
        APP_STORE_APPLE_ID: 6749488468
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get CocoaPods dependencies
        script: |
          if [ -f "Podfile" ]; then
            pod install
          else
            echo "Podfile bulunamadı, CocoaPods adımı atlanıyor"
          fi
      - name: Build for TestFlight (Debug Config)
        script: |
          echo "🏗️ Building debug version for TestFlight..."
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --config "Debug" \
            --archive-flags="-destination 'generic/platform=iOS'"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - samet.bicen@icloud.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - App Store Connect Users
        submit_to_app_store: false

  ios-no-signing-build:
    name: Envanto Barkod iOS Build (No Signing)
    max_build_duration: 45
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_WORKSPACE: "EnvantoBarkod.xcodeproj"
        XCODE_SCHEME: "EnvantoBarkod"
        BUNDLE_ID: "com.envanto.barcode.ios"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get CocoaPods dependencies
        script: |
          if [ -f "Podfile" ]; then
            pod install
          else
            echo "Podfile bulunamadı, CocoaPods adımı atlanıyor"
          fi
      - name: Build without code signing
        script: |
          # Code signing olmadan build
          xcodebuild \
            -project "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Debug \
            build \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            PROVISIONING_PROFILE_SPECIFIER=""
      - name: Create unsigned IPA
        script: |
          # Unsigned IPA oluştur (test amaçlı)
          echo "📦 Creating unsigned IPA for testing..."
          
          # Build klasörünü bul
          BUILD_DIR=$(find ~/Library/Developer/Xcode/DerivedData -name "*.app" -path "*/Build/Products/Debug-iphoneos/*" | head -1)
          
          if [ -n "$BUILD_DIR" ]; then
            echo "✅ App found: $BUILD_DIR"
            
            # IPA klasör yapısı oluştur
            mkdir -p build/Payload
            cp -r "$BUILD_DIR" build/Payload/
            
            # ZIP olarak paketleyip IPA yap
            cd build
            zip -r EnvantoBarkod-unsigned.ipa Payload/
            cd ..
            
            echo "✅ Unsigned IPA created: build/EnvantoBarkod-unsigned.ipa"
          else
            echo "❌ App build not found"
          fi
    artifacts:
      - build/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - samet.bicen@icloud.com
        notify:
          success: true
          failure: true

  ios-simulator-workflow:
    name: Envanto Barkod iOS Simulator Test
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_WORKSPACE: "EnvantoBarkod.xcodeproj"
        XCODE_SCHEME: "EnvantoBarkod"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get CocoaPods dependencies
        script: |
          if [ -f "Podfile" ]; then
            pod install
          else
            echo "Podfile bulunamadı, CocoaPods adımı atlanıyor"
          fi
      - name: Build for simulator
        script: |
          xcodebuild \
            -project "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
            build
    artifacts:
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - samet.bicen@icloud.com
        notify:
          success: true
          failure: true