workflows:
  final-clean-build:
    name: Final Clean iOS Build
    environment:
      groups:
        - admin
      xcode: latest
      cocoapods: default
    scripts:
      - name: Check environment
        script: |
          echo "Starting clean build process..."
          xcode-select --print-path
          xcodebuild -version
      - name: Initialize keychain
        script: keychain initialize
      - name: List available resources
        script: |
          echo "=== Certificates ==="
          app-store-connect certificates list --type IOS_DISTRIBUTION
          echo "=== Profiles ==="
          app-store-connect profiles list --type IOS_APP_STORE
      - name: Skip automatic signing - use manual
        script: |
          echo "Using manual code signing from Codemagic dashboard"
          echo "Certificates and profiles should be uploaded manually"
      - name: Build IPA with manual signing
        script: |
          # Provisioning profile'ı manuel olarak belirt
          xcode-project build-ipa \
            --project "EnvantoBarkod.xcodeproj" \
            --scheme "EnvantoBarkod" \
            --export-options-plist export_options.plist \
            PROVISIONING_PROFILE_SPECIFIER="EnvantoBarkod App Store" \
            CODE_SIGN_IDENTITY="iPhone Distribution"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM