workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      groups:
        - admin
      xcode: 16.4  # 'latest' yerine spesifik versiyon
      cocoapods: default
      vars:
        XCODE_PROJECT: "EnvantoBarkod.xcodeproj"
        XCODE_SCHEME: "EnvantoBarkod"
        BUNDLE_ID: "com.envanto.barcode.ios"
        APP_ID: "6749488468"  # App Store Connect'teki App ID'nizi yazın
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.envanto.barcode.ios
    integrations:
      app_store_connect: CodeMagic
    
    scripts:
      # Otomatik code signing için Codemagic'in built-in fonksiyonlarını kullan
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      
      - name: Set Info.plist values
        script: |
          # Build numarasını otomatik artır
          PLIST_PATH="EnvantoBarkod/Info.plist"
          CURRENT_BUILD_NUMBER=$(($(app-store-connect get-latest-build-number "$APP_ID") + 1))
          echo "Setting build number to $CURRENT_BUILD_NUMBER"
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $CURRENT_BUILD_NUMBER" "$PLIST_PATH"
      
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --project "EnvantoBarkod.xcodeproj" \
            --scheme "EnvantoBarkod" \
            --config "Release" \
            --export-method "app-store" \
            --archive-flags="-destination 'generic/platform=iOS' DEVELOPMENT_TEAM=6F974S63AX"
    
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.app.dSYM.zip
      - /tmp/xcodebuild_logs/*.log
      - ~/Library/Developer/Xcode/DerivedData//Build//*.xcarchive
    
    publishing:
      app_store_connect:
        auth: integration
        
        # TestFlight'a yükle
        submit_to_testflight: true
        
        # Beta test bilgileri (opsiyonel)
        beta_groups:
          - "Internal Testers"  # TestFlight'taki grup adınız
        
        # Otomatik olarak external test için gönder (opsiyonel)
        submit_to_app_store: false
        
        # Uygulamanın TestFlight'ta ne zaman expire olacağı (90 gün default)
        expire_build_submitted_for_review: true
      
      email:
        recipients:
          - samet.bicen@icloud.com  # Build sonucu için email
        notify:
          success: true
          failure: true