workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      groups:
        - admin
      xcode: latest
      vars:
        XCODE_WORKSPACE: "EnvantoBarkod.xcodeproj"
        XCODE_SCHEME: "EnvantoBarkod"
        BUNDLE_ID: "com.envanto.barcode.ios"
        # Sadece App Store Connect API bilgileri
        APP_STORE_CONNECT_ISSUER_ID: Encrypted(...) # Codemagic'te ekleyin
        APP_STORE_CONNECT_KEY_IDENTIFIER: Encrypted(...) # Codemagic'te ekleyin
        APP_STORE_CONNECT_PRIVATE_KEY: Encrypted(...) # Codemagic'te ekleyin
    scripts:
      - name: Set up keychain
        script: |
          keychain initialize
          
      - name: Set up App Store Connect API
        script: |
          mkdir -p ~/private_keys
          echo "$APP_STORE_CONNECT_PRIVATE_KEY" | base64 --decode > ~/private_keys/AuthKey_$APP_STORE_CONNECT_KEY_IDENTIFIER.p8
          
      - name: Fetch provisioning profiles (basit yöntem)
        script: |
          app-store-connect fetch-signing-files $BUNDLE_ID \
            --type IOS_APP_STORE \
            --create \
            --api-key-path ~/private_keys/AuthKey_$APP_STORE_CONNECT_KEY_IDENTIFIER.p8 \
            --api-issuer-id $APP_STORE_CONNECT_ISSUER_ID \
            --api-key-id $APP_STORE_CONNECT_KEY_IDENTIFIER
      
      - name: Build Archive
        script: |
          xcodebuild archive \
            -project EnvantoBarkod.xcodeproj \
            -scheme EnvantoBarkod \
            -destination "generic/platform=iOS" \
            -archivePath EnvantoBarkod.xcarchive \
            -configuration Release \
            CODE_SIGN_STYLE=Automatic \
            DEVELOPMENT_TEAM=6F974S63AX
            
      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath EnvantoBarkod.xcarchive \
            -exportPath . \
            -exportOptionsPlist export_options.plist
            
    artifacts:
      - "*.ipa"
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
      
    publishing:
      app_store_connect:
        api_key_path: ~/private_keys/AuthKey_$APP_STORE_CONNECT_KEY_IDENTIFIER.p8
        api_key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        api_key_issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        
        # TestFlight'a otomatik upload
        submit_to_testflight: true
        
        # Beta App Review için otomatik submit (opsiyonel)
        # beta_review: 
        #   default_locale: en-US
        #   beta_app_description: "EnvantoBarkod iOS uygulaması beta versiyonu"
        #   beta_app_feedback_email: "your-email@example.com"
        #   submit_for_beta_review: true
        
        # Test gruplarına otomatik dağıtım (opsiyonel)
        # beta_groups:
        #   - "Internal Testers"
        #   - "External Testers"