workflows:
  ios-build-only:
    name: iOS Build Only
    max_build_duration: 60
    environment:
      vars:
        XCODE_PROJECT: "EnvantoBarkod.xcodeproj"
        XCODE_SCHEME: "EnvantoBarkod"
        BUNDLE_ID: "com.envanto.barcode.ios"
        DEVELOPMENT_TEAM: "6F974S63AX"
      xcode: latest
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "main"
          include: true
    scripts:
      - name: Build iOS release
        script: |
          xcodebuild clean archive \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath build/EnvantoBarkod.xcarchive \
            DEVELOPMENT_TEAM=$DEVELOPMENT_TEAM \
            CODE_SIGN_STYLE=Automatic \
            -allowProvisioningUpdates
      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath build/EnvantoBarkod.xcarchive \
            -exportOptionsPlist export_options.plist \
            -exportPath build
    artifacts:
      - build/*.ipa
