workflows:
  ios-testflight-auto:
    name: iOS TestFlight
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Codemagic developer
    environment:
      groups:
        - app_store_credentials
      vars:
        XCODE_WORKSPACE: "EnvantoBarkod.xcodeproj"
        XCODE_SCHEME: "EnvantoBarkod"
        BUNDLE_ID: "com.envanto.barcode.ios"
      xcode: latest
    scripts:
      - name: Set up code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files $BUNDLE_ID --type IOS_APP_STORE --create
          keychain add-certificates
          xcode-project use-profiles
      - name: Build and archive
        script: |
          xcodebuild \
            -project "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            -archivePath build/app.xcarchive \
            archive
      - name: Export IPA
        script: |
          xcodebuild \
            -exportArchive \
            -archivePath build/app.xcarchive \
            -exportPath build \
            -exportOptionsPlist export_options.plist
      - name: Create export options
        script: |
          cat > export_options.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>teamID</key>
              <string>6F974S63AX</string>
          </dict>
          </plist>
          EOF
    artifacts:
      - build/*.ipa
      - build/app.xcarchive
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - App Store Connect Users
        submit_to_app_store: false