workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        XCODE_WORKSPACE: "EnvantoBarkod.xcodeproj"
        XCODE_SCHEME: "EnvantoBarkod"
        BUNDLE_ID: "com.envanto.barcode.ios"
        APP_STORE_CONNECT_ISSUER_ID: "f8637023-a8ad-468f-b46e-41e076d111e7"
        APP_STORE_CONNECT_KEY_IDENTIFIER: "79RJH98G9R"
        APP_STORE_CONNECT_PRIVATE_KEY: |
          -----BEGIN PRIVATE KEY-----
          MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg7YyV64dhmduUofi+y8D9vOZsuLv+ZflhzymrD0oJ+GWgCgYIKoZIzj0DAQehRANCAAQpesZeoMppKkkEyrdTG0KmCITvkII17qOtTHXZ0Rix2v7oH9DaLfgsav7/EwEIqXW0/w/ZIta/JONwG+2Z
          -----END PRIVATE KEY-----
      xcode: latest
    scripts:
      - name: Debug environment
        script: |
          echo "🔍 Environment check:"
          echo "BUNDLE_ID: $BUNDLE_ID"
          echo "APP_STORE_CONNECT_ISSUER_ID: $([ -n "$APP_STORE_CONNECT_ISSUER_ID" ] && echo "SET" || echo "NOT SET")"
          echo "APP_STORE_CONNECT_KEY_IDENTIFIER: $([ -n "$APP_STORE_CONNECT_KEY_IDENTIFIER" ] && echo "SET" || echo "NOT SET")"
          echo "APP_STORE_CONNECT_PRIVATE_KEY: $([ -n "$APP_STORE_CONNECT_PRIVATE_KEY" ] && echo "SET" || echo "NOT SET")"
      - name: Set up code signing
        script: |
          echo "🔐 Setting up code signing..."
          keychain initialize
          echo "📱 Fetching signing files..."
          app-store-connect fetch-signing-files $BUNDLE_ID --type IOS_APP_STORE --create --verbose
          echo "🔑 Adding certificates..."
          keychain add-certificates
          echo "📋 Using profiles..."
          xcode-project use-profiles

      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --project "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - samet.bicen@icloud.com
        notify:
          success: true
          failure: true
      # TestFlight upload will be added after successful build