workflows:
  envanto-barkod-final:
    name: Envanto Barkod Final Build
    environment:
      groups:
        - admin
      xcode: latest
      cocoapods: default
    scripts:
      - name: Check environment
        script: |
          echo "Starting build process..."
          xcode-select --print-path
          xcodebuild -version
      - name: Initialize keychain
        script: keychain initialize
      - name: Build IPA
        script: |
          xcodebuild archive \
            -project "EnvantoBarkod.xcodeproj" \
            -scheme "EnvantoBarkod" \
            -archivePath "build/EnvantoBarkod.xcarchive" \
            -configuration Release \
            DEVELOPMENT_TEAM=6F974S63AX \
            CODE_SIGN_STYLE=Manual \
            "CODE_SIGN_IDENTITY=iPhone Distribution" \
            "PROVISIONING_PROFILE_SPECIFIER=EnvantoBarkod App Store"
          
          xcodebuild -exportArchive \
            -archivePath "build/EnvantoBarkod.xcarchive" \
            -exportPath "build/ios/ipa" \
            -exportOptionsPlist export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM