workflows:
  ios-release-build:
    name: Envanto Barkod iOS Release Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.envanto.barcode.ios
      vars:
        BUNDLE_ID: "com.envanto.barcode.ios"
        XCODE_WORKSPACE: "EnvantoBarkod.xcodeproj"
        XCODE_SCHEME: "EnvantoBarkod"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get CocoaPods dependencies
        script: |
          # CocoaPods kullanılıyorsa
          # pod install
          echo "CocoaPods dependencies check completed"
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --config "Release"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

  ios-debug-build:
    name: Envanto Barkod iOS Debug Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      ios_signing:
        distribution_type: development
        bundle_identifier: com.envanto.barcode.ios
      vars:
        BUNDLE_ID: "com.envanto.barcode.ios"
        XCODE_WORKSPACE: "EnvantoBarkod.xcodeproj"
        XCODE_SCHEME: "EnvantoBarkod"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up debug code signing
        script: |
          xcode-project use-profiles
      - name: Build for testing
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --config "Debug"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

  ios-adhoc-build:
    name: Envanto Barkod iOS Ad Hoc Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      ios_signing:
        distribution_type: ad_hoc
        bundle_identifier: com.envanto.barcode.ios
      vars:
        BUNDLE_ID: "com.envanto.barcode.ios"
        XCODE_WORKSPACE: "EnvantoBarkod.xcodeproj"
        XCODE_SCHEME: "EnvantoBarkod"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up ad hoc code signing
        script: |
          xcode-project use-profiles
      - name: Build ad hoc ipa
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --config "Release"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log