workflows:
  final-clean-build:
    name: Final Clean iOS Build
    environment:
      groups:
        - admin
      xcode: latest
      cocoapods: default
    scripts:
      - name: Check environment
        script: |
          echo "Starting clean build process..."
          xcode-select --print-path
          xcodebuild -version
      - name: Initialize keychain
        script: keychain initialize
      - name: List available resources
        script: |
          echo "=== Certificates ==="
          app-store-connect certificates list --type IOS_DISTRIBUTION
          echo "=== Profiles ==="
          app-store-connect profiles list --type IOS_APP_STORE
      - name: Skip automatic signing - use manual
        script: |
          echo "Using manual code signing from Codemagic dashboard"
          echo "Certificates and profiles should be uploaded manually"
      - name: List available profiles and certificates
        script: |
          echo "=== Available Certificates ==="
          security find-identity -v -p codesigning
          echo "=== Available Provisioning Profiles ==="
          find ~/Library/MobileDevice/Provisioning\ Profiles -name "*.mobileprovision" -exec echo {} \; -exec security cms -D -i {} \; 2>/dev/null || echo "No profiles found"
      - name: Build with xcodebuild directly
        script: |
          # Direkt xcodebuild kullan
          xcodebuild archive \
            -project "EnvantoBarkod.xcodeproj" \
            -scheme "EnvantoBarkod" \
            -archivePath "build/EnvantoBarkod.xcarchive" \
            -configuration Release \
            DEVELOPMENT_TEAM=6F974S63AX \
            CODE_SIGN_STYLE=Manual \
            "CODE_SIGN_IDENTITY=iPhone Distribution" \
            "PROVISIONING_PROFILE_SPECIFIER=EnvantoBarkod App Store"
          
          # Export IPA
          xcodebuild -exportArchive \
            -archivePath "build/EnvantoBarkod.xcarchive" \
            -exportPath "build/ios/ipa" \
            -exportOptionsPlist export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM