workflows:
  ios-development-workflow:
    name: Envanto Barkod iOS Development Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_WORKSPACE: "EnvantoBarkod.xcodeproj"
        XCODE_SCHEME: "EnvantoBarkod"
        BUNDLE_ID: "com.envanto.barcode.ios"
        DEVELOPMENT_TEAM: "6F974S63AX"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get CocoaPods dependencies
        script: |
          if [ -f "Podfile" ]; then
            pod install
          else
            echo "Podfile bulunamadı, CocoaPods adımı atlanıyor"
          fi
      - name: Set up project for development build
        script: |
          # Xcode projesinde automatic signing ayarla
          /usr/libexec/PlistBuddy -c "Set :objects:AB1234567890123400000033:buildSettings:CODE_SIGN_STYLE Automatic" EnvantoBarkod.xcodeproj/project.pbxproj || true
          /usr/libexec/PlistBuddy -c "Set :objects:AB1234567890123400000034:buildSettings:CODE_SIGN_STYLE Automatic" EnvantoBarkod.xcodeproj/project.pbxproj || true
          /usr/libexec/PlistBuddy -c "Set :objects:AB1234567890123400000033:buildSettings:DEVELOPMENT_TEAM 6F974S63AX" EnvantoBarkod.xcodeproj/project.pbxproj || true
          /usr/libexec/PlistBuddy -c "Set :objects:AB1234567890123400000034:buildSettings:DEVELOPMENT_TEAM 6F974S63AX" EnvantoBarkod.xcodeproj/project.pbxproj || true
      - name: Build for development
        script: |
          xcodebuild \
            -project "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Debug \
            -destination 'generic/platform=iOS' \
            -allowProvisioningUpdates \
            -authenticationKeyPath ~/private_keys/AuthKey_*.p8 \
            -authenticationKeyID $APP_STORE_CONNECT_KEY_IDENTIFIER \
            -authenticationKeyIssuerID $APP_STORE_CONNECT_ISSUER_ID \
            archive \
            -archivePath build/EnvantoBarkod.xcarchive
      - name: Export IPA
        script: |
          xcodebuild \
            -exportArchive \
            -archivePath build/EnvantoBarkod.xcarchive \
            -exportPath build \
            -exportOptionsPlist export_options.plist
    artifacts:
      - build/*.ipa
      - build/EnvantoBarkod.xcarchive
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - samet.bicen@icloud.com
        notify:
          success: true
          failure: true

  ios-simulator-workflow:
    name: Envanto Barkod iOS Simulator Test
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_WORKSPACE: "EnvantoBarkod.xcodeproj"
        XCODE_SCHEME: "EnvantoBarkod"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get CocoaPods dependencies
        script: |
          if [ -f "Podfile" ]; then
            pod install
          else
            echo "Podfile bulunamadı, CocoaPods adımı atlanıyor"
          fi
      - name: Build for simulator
        script: |
          xcodebuild \
            -project "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
            build
    artifacts:
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - samet.bicen@icloud.com
        notify:
          success: true
          failure: true

  ios-device-build:
    name: Envanto Barkod iOS Device Build (SMTBCN 16pro)
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      ios_signing:
        distribution_type: development
        bundle_identifier: com.envanto.barcode.ios
      vars:
        XCODE_WORKSPACE: "EnvantoBarkod.xcodeproj"
        XCODE_SCHEME: "EnvantoBarkod"
        BUNDLE_ID: "com.envanto.barcode.ios"
        DEVELOPMENT_TEAM: "6F974S63AX"
        TARGET_DEVICE_UDID: "00008140-001469903469801C"
        TARGET_DEVICE_NAME: "SMTBCN 16pro"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Register device automatically
        script: |
          # Cihazı otomatik kaydet (eğer kayıtlı değilse)
          echo "📱 Registering device: $TARGET_DEVICE_NAME ($TARGET_DEVICE_UDID)"
      - name: Get CocoaPods dependencies
        script: |
          if [ -f "Podfile" ]; then
            pod install
          else
            echo "Podfile bulunamadı, CocoaPods adımı atlanıyor"
          fi
      - name: Build for specific device
        script: |
          # Automatic signing ile build
          xcodebuild \
            -project "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Debug \
            -destination "platform=iOS,id=$TARGET_DEVICE_UDID" \
            -allowProvisioningUpdates \
            DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
            CODE_SIGN_STYLE=Automatic \
            build
      - name: Create IPA for device
        script: |
          # Archive oluştur
          xcodebuild \
            -project "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Debug \
            -destination 'generic/platform=iOS' \
            -allowProvisioningUpdates \
            DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
            CODE_SIGN_STYLE=Automatic \
            archive \
            -archivePath build/EnvantoBarkod.xcarchive
          
          # Export options oluştur
          cat > export_options.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>development</string>
              <key>teamID</key>
              <string>$DEVELOPMENT_TEAM</string>
              <key>uploadBitcode</key>
              <false/>
              <key>compileBitcode</key>
              <false/>
              <key>signingStyle</key>
              <string>automatic</string>
          </dict>
          </plist>
          EOF
          
          # IPA export et
          xcodebuild \
            -exportArchive \
            -archivePath build/EnvantoBarkod.xcarchive \
            -exportPath build \
            -exportOptionsPlist export_options.plist
    artifacts:
      - build/*.ipa
      - build/EnvantoBarkod.xcarchive
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - samet.bicen@icloud.com
        notify:
          success: true
          failure: true

  ios-simple-build:
    name: Envanto Barkod iOS Simple Build
    max_build_duration: 45
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_WORKSPACE: "EnvantoBarkod.xcodeproj"
        XCODE_SCHEME: "EnvantoBarkod"
      xcode: latest
    scripts:
      - name: Simple build test
        script: |
          # En basit build - sadece compile kontrolü
          xcodebuild \
            -project "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Debug \
            build \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
    artifacts:
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - samet.bicen@icloud.com
        notify:
          success: true
          failure: true