workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      groups:
        - admin
      xcode: latest
    scripts:
      - name: Set up keychain
        script: keychain initialize
      - name: Set up provisioning profiles
        script: |
          PROFILES_HOME="$HOME/Library/MobileDevice/Provisioning Profiles"
          mkdir -p "$PROFILES_HOME"
          PROFILE_PATH=$(find /tmp -name "*.mobileprovision")
          cp "$PROFILE_PATH" "$PROFILES_HOME"
      - name: Set up signing certificate
        script: keychain add-certificates
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --project "EnvantoBarkod.xcodeproj" \
            --scheme "EnvantoBarkod"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM