workflows:
  envanto-barkod-clean-workflow:
    name: Envanto Barkod iOS Build
    environment:
      groups:
        - admin
      xcode: latest
      cocoapods: default
    scripts:
      - name: Check Xcode version
        script: xcode-select --print-path && xcodebuild -version
      - name: Set up keychain to be used for code signing using Codemagic CLI 'keychain' command
        script: keychain initialize
      - name: Convert and prepare private key
        script: |
          echo "$CERTIFICATE_PRIVATE_KEY" | base64 -d > /tmp/rsa_key.pem
          # RSA formatını PKCS#8'e çevir
          openssl pkcs8 -topk8 -inform PEM -outform PEM -nocrypt -in /tmp/rsa_key.pem -out /tmp/private_key.pem
          echo "Private key converted to PKCS#8 format"
          head -2 /tmp/private_key.pem
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "com.envanto.barcode.ios" \
          --type IOS_APP_STORE \
          --create \
          --certificate-key=/tmp/private_key.pem
      - name: Set up signing certificate
        script: keychain add-certificates
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Build App
        script: xcode-project build-ipa --project "EnvantoBarkod.xcodeproj" --scheme "EnvantoBarkod" --export-options-plist export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM