workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      groups:
        - admin
      xcode: latest
      vars:
        XCODE_WORKSPACE: "EnvantoBarkod.xcodeproj"
        XCODE_SCHEME: "EnvantoBarkod"
        BUNDLE_ID: "com.envanto.barcode.ios"
    integrations:
      app_store_connect: TestFlight Up
    scripts:
      - name: Set up provisioning profiles
        script: |
          app-store-connect fetch-signing-files $BUNDLE_ID --type IOS_APP_STORE --create
      
      - name: Set up signing certificate
        script: |
          keychain initialize
      
      - name: Build Archive
        script: |
          xcodebuild archive \
            -project EnvantoBarkod.xcodeproj \
            -scheme EnvantoBarkod \
            -destination "generic/platform=iOS" \
            -archivePath EnvantoBarkod.xcarchive \
            -configuration Release \
            CODE_SIGN_STYLE=Automatic \
            DEVELOPMENT_TEAM=6F974S63AX
            
      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath EnvantoBarkod.xcarchive \
            -exportPath . \
            -exportOptionsPlist export_options.plist
            
    artifacts:
      - "*.ipa"
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
      
    publishing:
      app_store_connect:
        auth: integration
        
        # TestFlight'a otomatik upload
        submit_to_testflight: true
        
        # Beta App Review için otomatik submit (opsiyonel)
        # beta_review: 
        #   default_locale: en-US
        #   beta_app_description: "EnvantoBarkod iOS uygulaması beta versiyonu"
        #   beta_app_feedback_email: "your-email@example.com"
        #   submit_for_beta_review: true
        
        # Test gruplarına otomatik dağıtım (opsiyonel)
        # beta_groups:
        #   - "Internal Testers"
        #   - "External Testers"