workflows:
  ios-development-build:
    name: Envanto Barkod iOS Development Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_WORKSPACE: "EnvantoBarkod.xcodeproj"
        XCODE_SCHEME: "EnvantoBarkod"
        BUNDLE_ID: "com.envanto.barcode.ios"
        APP_STORE_APPLE_ID: 6749488468
        DEVELOPMENT_TEAM: "6F974S63AX"
        # Automatic code signing için
        CODE_SIGN_STYLE: "Automatic"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get CocoaPods dependencies
        script: |
          if [ -f "Podfile" ]; then
            pod install
          else
            echo "Podfile bulunamadı, CocoaPods adımı atlanıyor"
          fi
      - name: Set up automatic code signing
        script: |
          echo "🔧 Setting up automatic code signing..."
          
          # Xcode project'te automatic signing ayarla
          /usr/libexec/PlistBuddy -c "Set :objects:AB1234567890123400000033:buildSettings:CODE_SIGN_STYLE Automatic" EnvantoBarkod.xcodeproj/project.pbxproj || true
          /usr/libexec/PlistBuddy -c "Set :objects:AB1234567890123400000034:buildSettings:CODE_SIGN_STYLE Automatic" EnvantoBarkod.xcodeproj/project.pbxproj || true
          /usr/libexec/PlistBuddy -c "Set :objects:AB1234567890123400000033:buildSettings:DEVELOPMENT_TEAM $DEVELOPMENT_TEAM" EnvantoBarkod.xcodeproj/project.pbxproj || true
          /usr/libexec/PlistBuddy -c "Set :objects:AB1234567890123400000034:buildSettings:DEVELOPMENT_TEAM $DEVELOPMENT_TEAM" EnvantoBarkod.xcodeproj/project.pbxproj || true
      - name: Increment build number
        script: |
          # Build number'ı otomatik artır
          BUILD_NUMBER=$(date +%Y%m%d%H%M)
          echo "🔢 Setting build number to: $BUILD_NUMBER"
          
          # Info.plist'te build number güncelle
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUMBER" Info.plist || true
      - name: Build for development with automatic signing
        script: |
          echo "🏗️ Building for development with automatic signing..."
          
          xcodebuild \
            -project "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Debug \
            -destination 'generic/platform=iOS' \
            -allowProvisioningUpdates \
            DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
            CODE_SIGN_STYLE=Automatic \
            PRODUCT_BUNDLE_IDENTIFIER="$BUNDLE_ID" \
            archive \
            -archivePath build/EnvantoBarkod.xcarchive
      - name: Export IPA for development
        script: |
          echo "📦 Exporting IPA for development..."
          
          # Export options oluştur
          cat > export_options.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>development</string>
              <key>teamID</key>
              <string>$DEVELOPMENT_TEAM</string>
              <key>uploadBitcode</key>
              <false/>
              <key>compileBitcode</key>
              <false/>
              <key>signingStyle</key>
              <string>automatic</string>
          </dict>
          </plist>
          EOF
          
          xcodebuild \
            -exportArchive \
            -archivePath build/EnvantoBarkod.xcarchive \
            -exportPath build \
            -exportOptionsPlist export_options.plist
    artifacts:
      - build/*.ipa
      - build/EnvantoBarkod.xcarchive
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - samet.bicen@icloud.com
        notify:
          success: true
          failure: true

  ios-no-signing-build:
    name: Envanto Barkod iOS Build (No Signing)
    max_build_duration: 45
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_WORKSPACE: "EnvantoBarkod.xcodeproj"
        XCODE_SCHEME: "EnvantoBarkod"
        BUNDLE_ID: "com.envanto.barcode.ios"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get CocoaPods dependencies
        script: |
          if [ -f "Podfile" ]; then
            pod install
          else
            echo "Podfile bulunamadı, CocoaPods adımı atlanıyor"
          fi
      - name: Build without code signing
        script: |
          # Code signing olmadan build
          xcodebuild \
            -project "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Debug \
            build \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            PROVISIONING_PROFILE_SPECIFIER=""
      - name: Create unsigned IPA
        script: |
          # Unsigned IPA oluştur (test amaçlı)
          echo "📦 Creating unsigned IPA for testing..."
          
          # Build klasörünü bul
          BUILD_DIR=$(find ~/Library/Developer/Xcode/DerivedData -name "*.app" -path "*/Build/Products/Debug-iphoneos/*" | head -1)
          
          if [ -n "$BUILD_DIR" ]; then
            echo "✅ App found: $BUILD_DIR"
            
            # IPA klasör yapısı oluştur
            mkdir -p build/Payload
            cp -r "$BUILD_DIR" build/Payload/
            
            # ZIP olarak paketleyip IPA yap
            cd build
            zip -r EnvantoBarkod-unsigned.ipa Payload/
            cd ..
            
            echo "✅ Unsigned IPA created: build/EnvantoBarkod-unsigned.ipa"
          else
            echo "❌ App build not found"
          fi
    artifacts:
      - build/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - samet.bicen@icloud.com
        notify:
          success: true
          failure: true

  ios-simulator-workflow:
    name: Envanto Barkod iOS Simulator Test
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_WORKSPACE: "EnvantoBarkod.xcodeproj"
        XCODE_SCHEME: "EnvantoBarkod"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get CocoaPods dependencies
        script: |
          if [ -f "Podfile" ]; then
            pod install
          else
            echo "Podfile bulunamadı, CocoaPods adımı atlanıyor"
          fi
      - name: Build for simulator
        script: |
          xcodebuild \
            -project "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
            build
    artifacts:
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - samet.bicen@icloud.com
        notify:
          success: true
          failure: true