workflows:
  fresh-envanto-workflow:
    name: Fresh Envanto Barkod Build
    environment:
      groups:
        - admin
      xcode: latest
      cocoapods: default
    scripts:
      - name: Check Xcode version
        script: xcode-select --print-path && xcodebuild -version
      - name: Set up keychain
        script: keychain initialize
      - name: Debug certificates and profiles
        script: |
          echo "=== Available Certificates ==="
          app-store-connect certificates list --type IOS_DISTRIBUTION
          echo "=== Available Profiles ==="
          app-store-connect profiles list --type IOS_APP_STORE
      - name: Fetch signing files (no create)
        script: |
          app-store-connect fetch-signing-files "com.envanto.barcode.ios" --type IOS_APP_STORE
      - name: Set up signing certificate
        script: keychain add-certificates
      - name: Set up code signing settings
        script: xcode-project use-profiles
      - name: Build App
        script: xcode-project build-ipa --project "EnvantoBarkod.xcodeproj" --scheme "EnvantoBarkod" --export-options-plist export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM